-- MySQL Script generated by MySQL Workbench
-- Tue Mar  7 12:04:36 2023
-- Model: Mosalapro  Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mosalapro
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mosalapro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mosalapro` ;
USE `mosalapro` ;

-- -----------------------------------------------------
-- Table `mosalapro`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mosalapro`.`country` (
  `country_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `country` VARCHAR(50) NOT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`country_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mosalapro`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mosalapro`.`city` (
  `city_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(50) NOT NULL,
  `country_id` SMALLINT UNSIGNED NOT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`city_id`),
  INDEX `idx_fk_country_id` (`country_id` ASC),
  CONSTRAINT `fk_city_country`
    FOREIGN KEY (`country_id`)
    REFERENCES `mosalapro`.`country` (`country_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mosalapro`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mosalapro`.`address` (
  `address_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(50) NOT NULL,
  `address2` VARCHAR(50) NULL DEFAULT NULL,
  `district` VARCHAR(20) NOT NULL,
  `city_id` SMALLINT UNSIGNED NOT NULL,
  `postal_code` VARCHAR(10) NULL DEFAULT NULL,
  `phone` VARCHAR(20) NOT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`address_id`),
  INDEX `idx_fk_city_id` (`city_id` ASC),
  CONSTRAINT `fk_address_city`
    FOREIGN KEY (`city_id`)
    REFERENCES `mosalapro`.`city` (`city_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mosalapro`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mosalapro`.`payment` (
  `payment_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `amount` DECIMAL(5,2) NOT NULL,
  `payment_date` DATETIME NOT NULL,
  `last_update` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`payment_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mosalapro`.`subscription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mosalapro`.`subscription` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `description` VARCHAR(245) NULL,
  `payment_payment_id` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_subscription_payment1_idx` (`payment_payment_id` ASC),
  CONSTRAINT `fk_subscription_payment1`
    FOREIGN KEY (`payment_payment_id`)
    REFERENCES `mosalapro`.`payment` (`payment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mosalapro`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mosalapro`.`user` (
  `user_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `address_id` SMALLINT UNSIGNED NOT NULL,
  `active` TINYINT(1) NOT NULL DEFAULT TRUE,
  `create_date` DATETIME NOT NULL,
  `last_update` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `subscription_id` SMALLINT UNSIGNED NOT NULL,
  `payment_payment_id` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `idx_fk_address_id` (`address_id` ASC),
  INDEX `idx_last_name` (`last_name` ASC),
  INDEX `fk_user_subscription1_idx` (`subscription_id` ASC),
  INDEX `fk_user_payment1_idx` (`payment_payment_id` ASC),
  CONSTRAINT `fk_customer_address`
    FOREIGN KEY (`address_id`)
    REFERENCES `mosalapro`.`address` (`address_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_subscription1`
    FOREIGN KEY (`subscription_id`)
    REFERENCES `mosalapro`.`subscription` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_payment1`
    FOREIGN KEY (`payment_payment_id`)
    REFERENCES `mosalapro`.`payment` (`payment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Table storing all customers. Holds foreign keys to the address table and the store table where this customer is registered.\n\nBasic information about the customer like first and last name are stored in the table itself. Same for the date the record was created and when the information was last updated.';


-- -----------------------------------------------------
-- Table `mosalapro`.`agent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mosalapro`.`agent` (
  `agent_id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `address_id` SMALLINT UNSIGNED NOT NULL,
  `picture` BLOB NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `active` TINYINT(1) NOT NULL DEFAULT TRUE,
  `username` VARCHAR(16) NOT NULL,
  `password` VARCHAR(40) BINARY NULL DEFAULT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`agent_id`),
  INDEX `idx_fk_address_id` (`address_id` ASC),
  CONSTRAINT `fk_staff_address`
    FOREIGN KEY (`address_id`)
    REFERENCES `mosalapro`.`address` (`address_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mosalapro`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mosalapro`.`category` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `last_updated` TIMESTAMP NOT NULL,
  `categorycol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mosalapro`.`service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mosalapro`.`service` (
  `service_id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cost` SMALLINT UNSIGNED NOT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `service_name` VARCHAR(45) NULL,
  `service_description` VARCHAR(255) NULL,
  `agent_staff_id` TINYINT UNSIGNED NOT NULL,
  `payment_payment_id` SMALLINT UNSIGNED NOT NULL,
  `address_address_id` SMALLINT UNSIGNED NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`service_id`),
  INDEX `idx_fk_address_id` (`cost` ASC),
  INDEX `fk_service_agent1_idx` (`agent_staff_id` ASC),
  INDEX `fk_service_payment1_idx` (`payment_payment_id` ASC),
  INDEX `fk_service_address1_idx` (`address_address_id` ASC),
  INDEX `fk_service_category1_idx` (`category_id` ASC),
  CONSTRAINT `fk_store_address`
    FOREIGN KEY (`cost`)
    REFERENCES `mosalapro`.`address` (`address_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_service_agent1`
    FOREIGN KEY (`agent_staff_id`)
    REFERENCES `mosalapro`.`agent` (`agent_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_service_payment1`
    FOREIGN KEY (`payment_payment_id`)
    REFERENCES `mosalapro`.`payment` (`payment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_service_address1`
    FOREIGN KEY (`address_address_id`)
    REFERENCES `mosalapro`.`address` (`address_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_service_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `mosalapro`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mosalapro`.`state`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mosalapro`.`state` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `state` VARCHAR(50) NOT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `country_country_id` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_state_country1_idx` (`country_country_id` ASC),
  CONSTRAINT `fk_state_country1`
    FOREIGN KEY (`country_country_id`)
    REFERENCES `mosalapro`.`country` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mosalapro`.`user_has_service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mosalapro`.`user_has_service` (
  `user_user_id` SMALLINT UNSIGNED NOT NULL,
  `service_service_id` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`user_user_id`, `service_service_id`),
  INDEX `fk_user_has_service_service1_idx` (`service_service_id` ASC),
  INDEX `fk_user_has_service_user1_idx` (`user_user_id` ASC),
  CONSTRAINT `fk_user_has_service_user1`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `mosalapro`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_service_service1`
    FOREIGN KEY (`service_service_id`)
    REFERENCES `mosalapro`.`service` (`service_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mosalapro`.`ratings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mosalapro`.`ratings` (
  `id` INT NOT NULL,
  `rating` SMALLINT NULL,
  `comment` VARCHAR(245) NULL,
  `agent_agent_id` TINYINT UNSIGNED NOT NULL,
  `user_user_id` SMALLINT UNSIGNED NOT NULL,
  INDEX `fk_ratings_agent1_idx` (`agent_agent_id` ASC),
  PRIMARY KEY (`user_user_id`),
  CONSTRAINT `fk_ratings_agent1`
    FOREIGN KEY (`agent_agent_id`)
    REFERENCES `mosalapro`.`agent` (`agent_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ratings_user1`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `mosalapro`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mosalapro`.`service_request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mosalapro`.`service_request` (
  `id` INT NOT NULL,
  `last_updated` TIMESTAMP NULL,
  `description` VARCHAR(245) NULL,
  `deadline` DATE NULL,
  `status` VARCHAR(45) NULL,
  `user_user_id` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_service_request_user1_idx` (`user_user_id` ASC),
  CONSTRAINT `fk_service_request_user1`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `mosalapro`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mosalapro`.`notifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mosalapro`.`notifications` (
  `id` INT NOT NULL,
  `titlle` VARCHAR(45) NULL,
  `content` VARCHAR(45) NULL,
  `user_user_id` SMALLINT UNSIGNED NOT NULL,
  `agent_agent_id` TINYINT UNSIGNED NOT NULL,
  `status` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_notifications_user1_idx` (`user_user_id` ASC),
  INDEX `fk_notifications_agent1_idx` (`agent_agent_id` ASC),
  CONSTRAINT `fk_notifications_user1`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `mosalapro`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notifications_agent1`
    FOREIGN KEY (`agent_agent_id`)
    REFERENCES `mosalapro`.`agent` (`agent_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mosalapro`.`login_attempts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mosalapro`.`login_attempts` (
  `id` INT NOT NULL,
  `user_email` VARCHAR(50) NULL,
  `created_at` TIMESTAMP NULL,
  `ip_address` VARCHAR(45) NULL,
  `location` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
